name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write  # Needed for committing on push events

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      # ✅ Ensure Pint has execute permissions
      - name: Make Pint Executable
        run: chmod +x vendor/bin/pint || true

      # ✅ Run Laravel Pint (PHP formatter)
      - name: Run Pint
        run: |
          echo "Running Laravel Pint..."
          if [ -f "vendor/bin/pint" ]; then
            vendor/bin/pint || echo "⚠️ Pint found issues or failed, continuing..."
          else
            echo "⚠️ Pint binary not found, skipping..."
          fi

      # ✅ Run Prettier or custom frontend formatter
      - name: Format Frontend
        run: |
          echo "Running npm format..."
          npm run format || echo "⚠️ Frontend formatting skipped or failed, continuing..."

      - name: Lint Frontend
        run: |
          echo "Running npm lint..."
          npm run lint || echo "⚠️ Frontend linting skipped or failed, continuing..."

      # ✅ Auto-commit formatting fixes only for direct pushes (not PRs)
      - name: Commit and Push Formatting Fixes
        if: github.event_name == 'push'  # Runs only when code is pushed directly to develop/main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: auto-fix code style issues"
          commit_options: '--no-verify'
          branch: ${{ github.ref_name }}
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          push_options: '--force'
